export const CHARACTER_ASSETS = [
  {
    assetId: 'CHR-PLY-001',
    groupId: 'CHR-PLY',
    kind: 'character',
    key: 'character_player',
    path: 'dist/assets/character_player.png',
    status: 'used',
  },
  {
    assetId: 'CHR-THF-001',
    groupId: 'CHR-THF',
    kind: 'character',
    key: 'thief',
    path: 'dist/assets/thief.png',
    status: 'used',
  },
  {
    assetId: 'CHR-FIN-001',
    groupId: 'CHR-FIN',
    kind: 'character',
    key: 'final_char',
    path: 'dist/assets/final_char.png',
    status: 'used',
  },
];

export const BACKGROUND_ASSETS = [
  {
    assetId: 'BG-SKY-001',
    groupId: 'BG-SKY',
    kind: 'background',
    key: 'bg_sky',
    path: 'dist/assets/bg_sky.png',
    status: 'used',
    targetMaps: ['sky'],
  },
  {
    assetId: 'BG-RUI-001',
    groupId: 'BG-RUI',
    kind: 'background',
    key: 'bg_ruins',
    path: 'dist/assets/bg_ruins.png',
    status: 'used',
    targetMaps: ['ruins'],
  },
  {
    assetId: 'BG-CIT-001',
    groupId: 'BG-CIT',
    kind: 'background',
    key: 'bg_city',
    path: 'dist/assets/bg_city.png',
    status: 'used',
    targetMaps: ['kerning'],
  },
  {
    assetId: 'BG-FOR-001',
    groupId: 'BG-FOR',
    kind: 'background',
    key: 'bg_forest',
    path: 'dist/assets/bg_forest.png',
    status: 'used',
    targetMaps: ['henesys'],
  },
  {
    assetId: 'BG-TOY-001',
    groupId: 'BG-TOY',
    kind: 'background',
    key: 'bg_toytown',
    path: 'dist/assets/bg_toytown.png',
    status: 'reserve',
    targetMaps: ['ellinia'],
  },
  {
    assetId: 'BG-TOY-002',
    groupId: 'BG-TOY',
    kind: 'background',
    key: 'bg_toytown_refresh',
    path: 'dist/assets/bg_toytown_refresh.png',
    status: 'used',
    targetMaps: ['ellinia'],
  },
  {
    assetId: 'BG-TPE-001',
    groupId: 'BG-TPE',
    kind: 'background',
    key: 'bg_taipei',
    path: 'dist/assets/bg_taipei.png',
    status: 'used',
    targetMaps: ['taipei'],
  },
  {
    assetId: 'BG-BOSS-001',
    groupId: 'BG-BOSS',
    kind: 'background',
    key: 'bg_boss_room',
    path: 'dist/assets/bg_boss_room.png',
    status: 'used',
    targetMaps: ['boss'],
  },
];

export const CANDIDATE_BACKGROUND_ASSETS = [
  {
    candidateId: 'CAND-BG-TOY-001',
    groupId: 'CAND-BG-TOY',
    kind: 'background',
    key: 'bg_toytown_refresh',
    plannedPath: 'dist/assets/bg_toytown_refresh.png',
    status: 'promoted-runtime',
    targetMaps: ['ellinia'],
    source: '參考用遊戲畫面/toy-TOWN_new (1).png',
  },
  {
    candidateId: 'CAND-BG-TPE-001',
    groupId: 'CAND-BG-TPE',
    kind: 'background',
    key: 'bg_taipei',
    plannedPath: 'dist/assets/bg_taipei.png',
    status: 'promoted-runtime',
    targetMaps: ['taipei'],
    source: '參考用遊戲畫面/Taipei_city.png',
  },
  {
    candidateId: 'CAND-BG-BOSS-001',
    groupId: 'CAND-BG-BOSS',
    kind: 'background',
    key: 'bg_boss_room',
    plannedPath: 'dist/assets/bg_boss_room.png',
    status: 'promoted-runtime',
    targetMaps: ['boss'],
    source: '遊戲畫面/boss_room.png',
  },
];

export const PLATFORM_ASSETS = [
  {
    assetId: 'PLT-LONG-001',
    groupId: 'PLT-LONG',
    kind: 'platform',
    key: 'platform_long',
    path: 'dist/assets/platform_long.png',
    status: 'used',
    targetMaps: ['henesys', 'ellinia', 'taipei'],
  },
];

export const MONSTER_ASSETS = [
  {
    assetId: 'MON-LEG-001',
    groupId: 'MON-LEG',
    kind: 'monster',
    key: 'monster_slime',
    path: 'dist/assets/monster_slime.png',
    status: 'used',
    monsterIds: ['slime', 'shadow-slime'],
    alignmentStatus: 'complete',
  },
  {
    assetId: 'MON-LEG-002',
    groupId: 'MON-LEG',
    kind: 'monster',
    key: 'monster_mushroom',
    path: 'dist/assets/monster_mushroom.png',
    status: 'used',
    monsterIds: ['mushroom'],
    alignmentStatus: 'complete',
  },
  {
    assetId: 'MON-LEG-003',
    groupId: 'MON-LEG',
    kind: 'monster',
    key: 'monster_snail',
    path: 'dist/assets/monster_snail.png',
    status: 'used',
    monsterIds: ['snail'],
    alignmentStatus: 'complete',
  },
  {
    assetId: 'MON-LEG-004',
    groupId: 'MON-LEG',
    kind: 'monster',
    key: 'monster_stump',
    path: 'dist/assets/monster_stump.png',
    status: 'used',
    monsterIds: ['stump'],
    alignmentStatus: 'complete',
  },
  {
    assetId: 'MON-LEG-005',
    groupId: 'MON-LEG',
    kind: 'monster',
    key: 'monster_boar',
    path: 'dist/assets/monster_boar.png',
    status: 'used',
    monsterIds: ['boar'],
    alignmentStatus: 'complete',
  },
  {
    assetId: 'MON-LEG-006',
    groupId: 'MON-LEG',
    kind: 'monster',
    key: 'monster_robot',
    path: 'dist/assets/monster_robot.png',
    status: 'used',
    monsterIds: ['robot'],
    alignmentStatus: 'complete',
  },
  {
    assetId: 'MON-LEG-007',
    groupId: 'MON-LEG',
    kind: 'monster',
    key: 'monster_skeleton',
    path: 'dist/assets/monster_skeleton.png',
    status: 'used',
    monsterIds: ['skeleton'],
    alignmentStatus: 'complete',
  },
  {
    assetId: 'MON-LEG-008',
    groupId: 'MON-LEG',
    kind: 'monster',
    key: 'monster_snake',
    path: 'dist/assets/monster_snake.png',
    status: 'used',
    monsterIds: ['snake'],
    alignmentStatus: 'complete',
  },
  {
    assetId: 'MON-LEG-009',
    groupId: 'MON-LEG',
    kind: 'monster',
    key: 'monster_dragon',
    path: 'dist/assets/monster_dragon.png',
    status: 'used',
    monsterIds: ['dragon'],
    alignmentStatus: 'complete',
  },
  {
    assetId: 'MON-LEG-010',
    groupId: 'MON-LEG',
    kind: 'monster',
    key: 'monster_cyclops',
    path: 'dist/assets/monster_cyclops.png',
    status: 'used',
    monsterIds: ['cyclops'],
    alignmentStatus: 'complete',
  },
  {
    assetId: 'MON-LEG-011',
    groupId: 'MON-LEG',
    kind: 'monster',
    key: 'monster_golem',
    path: 'dist/assets/monster_golem.png',
    status: 'used',
    monsterIds: ['golem'],
    alignmentStatus: 'complete',
  },
  {
    assetId: 'MON-LEG-012',
    groupId: 'MON-LEG',
    kind: 'monster',
    key: 'monster_mimic',
    path: 'dist/assets/monster_mimic.png',
    status: 'used',
    monsterIds: ['mimic'],
    alignmentStatus: 'complete',
  },
  {
    assetId: 'MON-NEW-001',
    groupId: 'MON-NEW',
    kind: 'monster',
    key: 'monster_new_0',
    path: 'dist/assets/monster_new_0.png',
    status: 'used',
    monsterIds: ['sky_imp'],
    alignmentStatus: 'complete',
  },
  {
    assetId: 'MON-NEW-002',
    groupId: 'MON-NEW',
    kind: 'monster',
    key: 'monster_new_1',
    path: 'dist/assets/monster_new_1.png',
    status: 'used',
    monsterIds: ['sky_bird'],
    alignmentStatus: 'complete',
  },
  {
    assetId: 'MON-NEW-003',
    groupId: 'MON-NEW',
    kind: 'monster',
    key: 'monster_new_2',
    path: 'dist/assets/monster_new_2.png',
    status: 'used',
    monsterIds: ['sky_puff'],
    alignmentStatus: 'complete',
  },
  {
    assetId: 'MON-NEW-004',
    groupId: 'MON-NEW',
    kind: 'monster',
    key: 'monster_new_3',
    path: 'dist/assets/monster_new_3.png',
    status: 'used',
    monsterIds: ['ruin_knight'],
    alignmentStatus: 'complete',
  },
  {
    assetId: 'MON-NEW-005',
    groupId: 'MON-NEW',
    kind: 'monster',
    key: 'monster_new_4',
    path: 'dist/assets/monster_new_4.png',
    status: 'used',
    monsterIds: ['ruin_golem'],
    alignmentStatus: 'complete',
  },
  {
    assetId: 'MON-NEW-006',
    groupId: 'MON-NEW',
    kind: 'monster',
    key: 'monster_new_5',
    path: 'dist/assets/monster_new_5.png',
    status: 'used',
    monsterIds: ['ruin_wraith'],
    alignmentStatus: 'complete',
  },
  {
    assetId: 'MON-NEW-007',
    groupId: 'MON-NEW',
    kind: 'monster',
    key: 'monster_new_6',
    path: 'dist/assets/monster_new_6.png',
    status: 'used',
    monsterIds: ['city_thug'],
    alignmentStatus: 'complete',
  },
  {
    assetId: 'MON-BIG-001',
    groupId: 'MON-BIG',
    kind: 'monster',
    key: 'monster_big_0',
    path: 'dist/assets/monster_big_0.png',
    status: 'used',
    monsterIds: ['ruin_beast'],
    alignmentStatus: 'complete',
  },
  {
    assetId: 'MON-BIG-002',
    groupId: 'MON-BIG',
    kind: 'monster',
    key: 'monster_big_1',
    path: 'dist/assets/monster_big_1.png',
    status: 'used',
    monsterIds: ['ruin_giant'],
    alignmentStatus: 'complete',
  },
  {
    assetId: 'MON-BIG-003',
    groupId: 'MON-BIG',
    kind: 'monster',
    key: 'monster_big_2',
    path: 'dist/assets/monster_big_2.png',
    status: 'used',
    monsterIds: ['city_mech'],
    alignmentStatus: 'complete',
  },
  {
    assetId: 'MON-BIG-004',
    groupId: 'MON-BIG',
    kind: 'monster',
    key: 'monster_big_3',
    path: 'dist/assets/monster_big_3.png',
    status: 'used',
    monsterIds: ['city_beast'],
    alignmentStatus: 'complete',
  },
  {
    assetId: 'MON-BIG-005',
    groupId: 'MON-BIG',
    kind: 'monster',
    key: 'monster_big_4',
    path: 'dist/assets/monster_big_4.png',
    status: 'used',
    monsterIds: ['city_elite'],
    alignmentStatus: 'complete',
  },
  {
    assetId: 'MON-MB-001',
    groupId: 'MON-MB',
    kind: 'miniboss',
    key: 'miniboss_0',
    path: 'dist/assets/miniboss_0.png',
    status: 'used',
    monsterIds: ['city_boss1'],
    alignmentStatus: 'complete',
  },
  {
    assetId: 'MON-MB-002',
    groupId: 'MON-MB',
    kind: 'miniboss',
    key: 'miniboss_1',
    path: 'dist/assets/miniboss_1.png',
    status: 'used',
    monsterIds: ['city_boss2'],
    alignmentStatus: 'complete',
  },
];

export const NPC_ASSETS = [
  {
    assetId: 'NPC-NEW-000',
    groupId: 'NPC-NEW',
    kind: 'npc',
    key: 'npc_new_0',
    path: 'dist/assets/npc_new_0.png',
    status: 'used',
  },
  {
    assetId: 'NPC-NEW-001',
    groupId: 'NPC-NEW',
    kind: 'npc',
    key: 'npc_new_1',
    path: 'dist/assets/npc_new_1.png',
    status: 'used',
  },
  {
    assetId: 'NPC-NEW-002',
    groupId: 'NPC-NEW',
    kind: 'npc',
    key: 'npc_new_2',
    path: 'dist/assets/npc_new_2.png',
    status: 'used',
  },
  {
    assetId: 'NPC-NEW-003',
    groupId: 'NPC-NEW',
    kind: 'npc',
    key: 'npc_new_3',
    path: 'dist/assets/npc_new_3.png',
    status: 'used',
  },
  {
    assetId: 'NPC-NEW-004',
    groupId: 'NPC-NEW',
    kind: 'npc',
    key: 'npc_new_4',
    path: 'dist/assets/npc_new_4.png',
    status: 'used',
  },
  {
    assetId: 'NPC-NEW-005',
    groupId: 'NPC-NEW',
    kind: 'npc',
    key: 'npc_new_5',
    path: 'dist/assets/npc_new_5.png',
    status: 'used',
  },
];

export const BOSS_ASSETS = [
  {
    assetId: 'BOSS-MAIN-001',
    groupId: 'BOSS-MAIN',
    kind: 'boss',
    key: 'boss_main',
    path: 'dist/assets/boss_main.png',
    status: 'used',
    targetMaps: ['boss'],
  },
];

export const PRELOAD_IMAGE_ASSETS = [
  ...CHARACTER_ASSETS,
  ...BACKGROUND_ASSETS,
  ...PLATFORM_ASSETS,
  ...MONSTER_ASSETS,
  ...BOSS_ASSETS,
  ...NPC_ASSETS,
];

export const PENDING_ALIGNMENT_ASSETS = MONSTER_ASSETS.filter(
  (asset) => asset.alignmentStatus === 'pending-alignment',
);
